CREATE TABLE USER (
    USER_ID     VARCHAR2(15),
    USER_PW     VARCHAR2(20) NOT NULL,
    USER_NAME   VARCHAR2(20) NOT NULL,
    BIRTH_DATE  VARCHAR2(8),
    USER_EMAIL  VARCHAR2(20),
    USER_PHONE  NUMBER(15),
    CONSTRAINT  PK_USER_ID PRIMARY KEY(USER_ID)   
);